# Generated by Django 6.0.5 on 2026-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='channelconfig',
            unique_together={('guild_id', 'channel_id')},
        ),
    ]
